apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vcluster
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Vclusters project
  sourceRepos:
  - https://charts.loft.sh 
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'