apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: product-policy
  namespace: vcluster-vcteam-a
spec:
  podSelector: 
    matchLabels: {}
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector: {}
            